name: Windows Initial Configuration

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: thatisuday/go-cross-build@v1
      with:
        platforms: 'windows/amd64'
        name: 'WindowsInitial'
        dest: 'build'
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: WindowsInitial-windows-amd64.exe
        path: ./build/WindowsInitial-windows-amd64.exe
        if-no-files-found: error
        retention-days: 1
  release:
    name: Release WindowsInitial new version
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: WindowsInitial-windows-amd64.tar.gz
      - name: Archive artifact
        uses: thedoctor0/zip-release@master
        with:
          filename: app.zip
      - name: Create Github Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number}}
          release_name: Release V${{ github.run_number }}
      - name: Upload asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app.zip
          asset_name: app-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      
