name: Windows Initial Configuration

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: "Build"
      uses: thatisuday/go-cross-build@v1
      with:
        platforms: 'windows/amd64'
        name: 'WindowsInitial'
        dest: 'build'
      - uses: actions/checkout@v2
      - uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'windows/amd64'
          name: 'WindowsInitial'
          dest: 'build'
      - name: Create Github Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number}}
          release_name: Release V${{ github.run_number }}
      - name: Upload asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app.zip
          asset_name: app-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      
