name: Windows Initial Configuration

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
        platforms: 'windows/amd64'
        package: ''
        name: 'WindowsInitial'
        compress: 'true'
        dest: 'dist'
      
